CREATE TABLE IF NOT EXISTS "aparments_for_rent" (
	"id" serial PRIMARY KEY NOT NULL,
	"url" varchar(255),
	"title" varchar(255),
	"price" numeric,
	"size" numeric,
	"location" varchar(255),
	"city" varchar(255),
	"year_of_construction" integer,
	"floor" integer,
	"total_floors" integer,
	"num_of_bathrooms" numeric,
	"num_of_rooms" numeric,
	"registered" boolean,
	"heating_central" boolean,
	"heating_ta" boolean,
	"heating_air_conditioning" boolean,
	"heating_floor" boolean,
	"heating_electricity" boolean,
	"heating_gas" boolean,
	"heating_solid_fuel" boolean,
	"heating_other" boolean,
	"elevator" boolean,
	"terrace" boolean,
	"parking" boolean,
	"garage" boolean
);

CREATE TABLE IF NOT EXISTS "aparments_for_sale" (
	"id" serial PRIMARY KEY NOT NULL,
	"url" varchar(255),
	"title" varchar(255),
	"price" numeric,
	"size" numeric,
	"location" varchar(255),
	"city" varchar(255),
	"year_of_construction" integer,
	"floor" integer,
	"total_floors" integer,
	"num_of_bathrooms" numeric,
	"num_of_rooms" numeric,
	"registered" boolean,
	"heating_central" boolean,
	"heating_ta" boolean,
	"heating_air_conditioning" boolean,
	"heating_floor" boolean,
	"heating_electricity" boolean,
	"heating_gas" boolean,
	"heating_solid_fuel" boolean,
	"heating_other" boolean,
	"elevator" boolean,
	"terrace" boolean,
	"parking" boolean,
	"garage" boolean
);

CREATE TABLE IF NOT EXISTS "houses_for_rent" (
	"id" serial PRIMARY KEY NOT NULL,
	"url" varchar(255),
	"title" varchar(255),
	"price" numeric,
	"size" numeric,
	"location" varchar(255),
	"city" varchar(255),
	"year_of_construction" integer,
	"land_surface" numeric,
	"total_floors" integer,
	"num_of_bathrooms" numeric,
	"num_of_rooms" numeric,
	"registered" boolean,
	"heating_central" boolean,
	"heating_ta" boolean,
	"heating_air_conditioning" boolean,
	"heating_floor" boolean,
	"heating_electricity" boolean,
	"heating_gas" boolean,
	"heating_solid_fuel" boolean,
	"heating_other" boolean,
	"elevator" boolean,
	"terrace" boolean,
	"parking" boolean,
	"garage" boolean
);

CREATE TABLE IF NOT EXISTS "houses_for_sale" (
	"id" serial PRIMARY KEY NOT NULL,
	"url" varchar(255),
	"title" varchar(255),
	"price" numeric,
	"size" numeric,
	"location" varchar(255),
	"city" varchar(255),
	"year_of_construction" integer,
	"land_surface" numeric,
	"total_floors" integer,
	"num_of_bathrooms" numeric,
	"num_of_rooms" numeric,
	"registered" boolean,
	"heating_central" boolean,
	"heating_ta" boolean,
	"heating_air_conditioning" boolean,
	"heating_floor" boolean,
	"heating_electricity" boolean,
	"heating_gas" boolean,
	"heating_solid_fuel" boolean,
	"heating_other" boolean,
	"elevator" boolean,
	"terrace" boolean,
	"parking" boolean,
	"garage" boolean
);

CREATE UNIQUE INDEX IF NOT EXISTS "idx_aparments_for_rent_url" ON "aparments_for_rent" ("url");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_aparments_for_sale_url" ON "aparments_for_sale" ("url");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_houses_for_rent_url" ON "houses_for_rent" ("url");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_houses_for_sale_url" ON "houses_for_sale" ("url");